site_name: Contoso Corporation

docs_dir: 'docs'

nav:
  - Home: 'index.md'
  - 'File Handler':
    - 'Overview': 'file-handler/index.md'
    - 'Tech Details': 'file-handler/tech-details.md'
  - 'Remote Document Generation':
    - 'Overview': 'list-view-invoke/index.md'
    - 'Setup': 'list-view-invoke/setup.md'
    - 'Enable Multi-tenant Auth': 'list-view-invoke/multi-tenant.md'
    - 'Tech Details': 'list-view-invoke/tech-details.md'
  - 'OneDrive as your application files repository'
    - 'Overview': 'onedrivefiles/index.md'
    - 'Tech Details': 'onedrivefiles/tech-details.md'


theme:
  name: 'material'
  palette:
    primary: 'blue'
  logo: 'img/logo.png'
  feature:
    tabs: true

extra_css:
  - 'css/extra.css'

markdown_extensions:
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - markdownextradata

repo_url: https://github.com/pnp/contoso

edit_uri: tree/main/docs

site_url: https://pnp.github.io/contoso/
